image: 'maven:3.5.3-jdk-8'
before_script:
    - 'source ./project.sh'
stages:
 - test
 - build
services:
    - 'mysql:5.5'
variables:
     MYSQL_DATABASE: movieDb;
     MYSQL_CI_URL: jdbc:mysql://mysql/newsData
     MYSQL_USER: app_root
     MYSQL_ROOT_PASSWORD: root
     MYSQL_PASSWORD: root
cache:
 paths:
    - .m2/repository/
    - target
maven-test:
 stage: test
 script: "mvn test -B"
maven-build:
 stage: build
 script: "mvn package -U"
 artifacts:
   paths:
     - 'target/*.jar'
